runtime: nodejs22
env: standard
instance_class: F1
automatic_scaling:
  min_instances: 0
  max_instances: 1
env_variables:
  MONGO_URI: "mongodb+srv://fadillamaksum650:codingCampCapstone@cluster0.dhbnidk.mongodb.net/Capstone?retryWrites=true&w=majority&appName=Cluster0"
  CLOUDINARY_CLOUD_NAME: "dpmk6oieq"
  CLOUDINARY_API_KEY: "122214149943984"
  CLOUDINARY_API_SECRET: "ZImVuqN2BqJvq2nqA5ZjOXJXQmo"
  JWT_SECRET: "yourSuperSecretKey"
handlers:
  - url: /.*
    script: auto
